//This is the original index file that enables the generated conspiracy to be printed out on  a thermal printer once the AI API has generated it

import Head from "next/head";
import ConspiracyPreview from "@/components/ConspiracyPreview";
import { conspiracyData } from "@/data/conspiracyData";
import { useState, useEffect, useRef } from "react";
import axios from "axios";
import Typewriter from 'typewriter-effect';

//Shuffle cards each time game starts
function shuffleArray(array) {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}



export default function Home() {
  const [pickedCount, setPickedCount] = useState(0);
  const [selectedPrompts, setSelectedPrompts] = useState([]);
  const [story, setStory] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [showInstructions, setShowInstructions] = useState(true);
  const [showCards, setShowCards] = useState(false);
  const [showEndCount, setEndCount] = useState(false);
  const [showCardCount, setShowCardCount] = useState(true);
  const [shuffledData, setShuffledData] = useState([]);
  const delay = ms => new Promise(res => setTimeout(res, ms));
  
  //Hide Intro Instructions
  const handleHideInstructions = () => {
    //background sound for exhbition mode
    let BgAudioRef = new Audio('./sounds/final-bg.wav');
    setShowInstructions(false);
    setShowCards(true);
    BgAudioRef.play();
    BgAudioRef.loop = true;    
  }  
   
 
  const handlePromptSelect = (prompt, isSelected) => {
    if (typeof prompt !== 'string' || prompt.trim() === '') {
      console.error('Invalid prompt received:', prompt);
      return;
    }
    if (isSelected && selectedPrompts.length < 10) {
      setSelectedPrompts((prev) => {
        if (prev.includes(prompt)) return prev; // Prevent duplicate picking
        const newPrompts = [...prev, prompt].slice(0, 10);
        console.log('Updated selectedPrompts:', newPrompts, 'Picked count:', pickedCount + 1); 
        return newPrompts;
      });
    }
  };

  useEffect(() => {
    console.log('Current selectedPrompts:', selectedPrompts, 'pickedCount:', pickedCount); // Debug
    if (pickedCount === 10 && !loading && !story) {
      setShowCardCount(false);
      setEndCount(true);
      if (selectedPrompts.length !== 10) {
        console.error('Mismatch: pickedCount is 10 but selectedPrompts length is', selectedPrompts.length);
        setError('Error: Please select exactly 10 prompts.');
        return;
      }
      const generateStory = async () => {
        setLoading(true);
        setError("");
        try {
          console.log('Sending prompts to API:', selectedPrompts); // Debug
          const response = await axios.post("/api/generate-story-new", {
            prompts: selectedPrompts,
            model: "grok-3",
          });
          console.log('API response:', response.data); // Debug
          setStory(response.data.story);
        } catch (err) {
          console.error('Frontend Error:', err.response?.data || err.message);
          setError(err.response?.data?.error || "Failed to generate story. Please try again.");
        } finally {
          setLoading(false);
          //reload page for print mode
          await delay(40000);
          window.location.reload();
        }
      };
      generateStory();
    }
  }, [pickedCount, selectedPrompts]);

  useEffect(() => {
    const shuffled = shuffleArray(conspiracyData);
    console.log('Shuffled data:', shuffled.map(item => item.prompt)); 
    setShuffledData(shuffled);
  }, []);

  return (
    <>
      <Head>
        <title>Abulafia 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <div className="main-div">
            {showInstructions && (
              <div className="instructions-div">
                <div className="instructions">
                  <h1 className="instructions-title">Abulafia</h1>
                  <div className="instructions-para">
                    <Typewriter
                      onInit={(typewriter) => {
                        typewriter.changeDelay(40)
                        typewriter.typeString('Abulafia is a reinterpretation of the software in Umberto Eco’s Foucault’s Pendulum. In the novel the protagonists use Abulafia to randomly connect historical events, occult texts, and mythologies to build a conspiracy theory that becomes known as The Plan. In the new version of Abulafia the player takes the responsibility of the protagonists, but rather than serving as a literary editor the player inhabits the role of a gambler. The gambler chooses 10 cards from a shuffled deck, each containing a conspiracy ranging from ancient to modern. Once 10 cards are chosen Abulafia will create a new conspiracy linking all the cards together. The gambler is invited to add it to The Plan.')
                          .callFunction(() => {
                            console.log('String typed out!');
                          })
                          .start();
                      }}
                    />
                  </div>
                  <button onClick={handleHideInstructions} className="instructions-button">
                    Begin
                  </button>
                </div>
              </div>
            )}

            <div className="title-div">
              <h1 className="main-title">Abulafia</h1>
                {showCardCount && (
                  <h1 className="card-counter">
                    Select <span id="card-counter">{10 - pickedCount}</span> More Cards
                  </h1>
                )}
                {showEndCount && (
                  <h1 className="card-counter">
                    Await Conspiracy
                  </h1>
                )}
            </div>

            
            {showCards && (
              <div className="card-div">
                {shuffledData.map((item, index) => (
                  <ConspiracyPreview
                    key={index}
                    image={item.image}
                    title={item.title}
                    prompt={item.prompt}
                    description={item.description}
                    pickedCount={pickedCount}
                    setPickedCount={setPickedCount}
                    onSelect={handlePromptSelect}
                    isSelected={selectedPrompts.includes(item.prompt)}
                  />
                ))}
              </div>
            )}
            

            
             {/* {loading && <p className="story-div">Generating conspiracy...</p>}
            {error && <p>{error}</p>}
            {story && (
              <div className="story-div">
                
                <p>{story}</p>
              </div>
            )}  */}
            
          </div>
        </main>
      </div>
    </>
  );
}